use UNIVER;

declare @one nvarchar(10), @all nvarchar(200) = ' ';
declare Out cursor for select SUBJECT from SUBJECT;
open Out
fetch Out into @one;
print 'Вывод предметов'
while @@FETCH_STATUS = 0
begin
set @all = RTRIM(@one) + ', ' + @all
fetch Out into @one
end 
print RTRIM(@all) + ' Конец перечисления'
close Out

-----------------------------------2>
DECLARE OUTLOCAL CURSOR LOCAL FOR SELECT SUBJECT FROM SUBJECT
DECLARE @first NVARCHAR(10), @al NVARCHAR(200) = ' ';

OPEN OUTLOCAL
FETCH OUTLOCAL INTO @first
PRINT '1. ' + @first
GO
DECLARE @first NVARCHAR(10), @al NVARCHAR(200) = ' ';
FETCH OUTLOCAL INTO @first
PRINT '2. ' + @first
GO

DECLARE PULS CURSOR GLOBAL FOR  SELECT SUBJECT FROM SUBJECT
DECLARE @SUB1 NVARCHAR(10);
OPEN PULS;
FETCH PULS INTO @SUB1;
PRINT RTRIM(@SUB1)+' Выполнено ';
GO
DECLARE @SUB2 NVARCHAR(10);
FETCH PULS INTO @SUB2;
PRINT RTRIM(@SUB2)+'  Выполнено ';
GO
DECLARE @SUB3 NVARCHAR(10);
FETCH PULS INTO @SUB3;
PRINT RTRIM(@SUB3)+' Выполнено ';
CLOSE PULS;

-----------------------------------3>
DECLARE @PUL CHAR(10), @GEN CHAR(2), @NAME CHAR(30);
DECLARE TEACHERS CURSOR LOCAL DYNAMIC FOR SELECT PULPIT, GENDER, TEACHER_NAME FROM TEACHER WHERE PULPIT='ИСиТ';
OPEN TEACHERS;
PRINT 'Количество преподавателей: '+CAST(@@CURSOR_ROWS AS VARCHAR(5));
INSERT INTO TEACHER  (TEACHER, TEACHER_NAME, GENDER, PULPIT)
VALUES ('БАВ','Бойков Антон Владимирович', 'м', 'ИСиТ');
UPDATE TEACHER SET TEACHER_NAME = 'Бойков Александр Владимирович' WHERE TEACHER = 'БАВ';
FETCH TEACHERS INTO @PUL, @GEN, @NAME;
PRINT 'Информация: '+RTRIM(@PUL)+' '+RTRIM(@GEN)+' '+RTRIM(@NAME);
WHILE @@FETCH_STATUS=0
BEGIN
FETCH TEACHERS INTO @PUL, @GEN, @NAME;
PRINT 'Информация: '+RTRIM(@PUL)+' '+RTRIM(@GEN)+' '+RTRIM(@NAME);
END;
CLOSE TEACHERS;
DELETE TEACHER WHERE TEACHER = 'БАВ';

-----------------------------------4>

DECLARE @TYPE NVARCHAR(20), @CAPACITY NVARCHAR(20)
DECLARE LOCAL CURSOR GLOBAL STATIC SCROLL FOR SELECT AUDITORIUM_TYPE, AUDITORIUM_CAPACITY FROM AUDITORIUM

OPEN LOCAL
PRINT 'Аудитории: '
FETCH LOCAL INTO @TYPE, @CAPACITY
WHILE @@FETCH_STATUS = 0
BEGIN
PRINT '' + @TYPE + ' ' + @CAPACITY
FETCH LOCAL INTO @TYPE, @CAPACITY
END
CLOSE LOCAL

OPEN LOCAL
PRINT 'Первая строка: '
FETCH FIRST FROM LOCAL INTO @TYPE, @CAPACITY
PRINT '' + @TYPE + @CAPACITY

PRINT 'Вторая с начала (ABSOLUTE)'
FETCH ABSOLUTE 2 FROM LOCAL INTO @TYPE, @CAPACITY
PRINT '' + @TYPE + @CAPACITY

PRINT 'Пятая с конца (ABSOLUTE)'
FETCH ABSOLUTE -5 FROM LOCAL INTO @TYPE, @CAPACITY
PRINT '' + @TYPE + @CAPACITY

PRINT 'Вторая от текущей (RELATIVE)'
FETCH RELATIVE 2 FROM LOCAL INTO @TYPE, @CAPACITY
PRINT '' + @TYPE + @CAPACITY

PRINT 'Следующая строка: '
FETCH NEXT FROM LOCAL INTO @TYPE, @CAPACITY
PRINT '' + @TYPE + @CAPACITY

PRINT 'Предыдущая строка: '
FETCH PRIOR FROM LOCAL INTO @TYPE, @CAPACITY
PRINT '' + @TYPE + @CAPACITY

PRINT 'Последняя строка: '
FETCH LAST FROM LOCAL INTO @TYPE, @CAPACITY
PRINT '' + @TYPE + @CAPACITY

CLOSE LOCAL
-----------------------------------5>

INSERT INTO FACULTY (FACULTY, FACULTY_NAME)
VALUES ('ISIT', 'ISITCHICK');
DECLARE E_CURRENT CURSOR LOCAL SCROLL DYNAMIC FOR SELECT FACULTY, 
FACULTY_NAME FROM FACULTY FOR UPDATE;
DECLARE @FAC VARCHAR(5), @FULL VARCHAR(50);
OPEN E_CURRENT
FETCH FIRST FROM E_CURRENT INTO @FAC, @FULL;
PRINT @FAC + ' ' + @FULL;
UPDATE FACULTY SET FACULTY = 'MOBILE' WHERE CURRENT OF E_CURRENT;
FETCH FIRST FROM E_CURRENT INTO @FAC, @FULL;
PRINT @FAC + ' ' + @FULL;
CLOSE E_CURRENT;
GO
SELECT * FROM FACULTY;
DELETE FACULTY WHERE  FACULTY = 'MOBILE'

-----------------------------------6>

USE UNIVER;
DECLARE @NOTE INT, @NAME NVARCHAR(50), @FACULTY NVARCHAR(20);
DECLARE GOODBYE CURSOR DYNAMIC GLOBAL FOR
SELECT PROGRESS.NOTE, STUDENT.NAME, GROUPS.FACULTY
FROM PROGRESS 
JOIN STUDENT ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
JOIN GROUPS ON STUDENT.IDGROUP = GROUPS.IDGROUP
OPEN GOODBYE
FETCH GOODBYE INTO @NOTE, @NAME, @FACULTY
WHILE @@FETCH_STATUS = 0
BEGIN
PRINT 'Оценка ' + CAST(@NOTE AS NVARCHAR(10)) + ' - ' + @NAME + ' - ' + @FACULTY
FETCH GOODBYE INTO @NOTE, @NAME, @FACULTY
IF @NOTE <4
DELETE PROGRESS WHERE CURRENT OF GOODBYEE
END
CLOSE GOODBYE