use UNIVER;
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRANSACTION
SELECT SUBJECT FROM SUBJECT WHERE SUBJECT = 'สั'
--------T1---------
--------T2---------
SELECT CASE
WHEN PULPIT = 'ศั่า' THEN 'INSERT'  
ELSE ' ' 
END,
SUBJECT FROM SUBJECT WHERE PULPIT = 'ศั่า'
ROLLBACK